DefaultContentLanguage = "en"
author = "Logan Bek"
baseURL = "https://gohugo.io/"
copyright = "Copyright © 2021, Kogecoin; all rights reserved."
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 2
theme = "github.com/jonathanjanssens/hugo-casper3"
title = "Kogecoin on Polygon"
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "image-credit"
name = "Image Credit"
url = "/image-credit/"
weight = 20
[[menu.main]]
identifier = "github-repo-theme"
name = "Get Theme on Github"
url = "https://github.com/jonathanjanssens/hugo-casper3"
weight = 30
[[menu.main]]
identifier = "author"
name = "Author Homepage"
url = "https://jonathanjanssens.com"
weight = 40
[params]
description = "Kogecoin.io - Informational site for Kogecoin.io + Kogefarm.io on Polygon"
facebook = ""
github = "https://github.com/kogecoin"
logo = "/images/ghost-transparent.png"
mainSections = ["post"]
twitter = "https://twitter.com/kogecoin"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
